const fs = require('fs');
const path = require('path');

const dbFilePath = path.join(__dirname, '../js/services/db.js');
let dbContent = fs.readFileSync(dbFilePath, 'utf8');

// 30 Artworks Data structured across the 3 official divisions
const divisions = [
  {
    range: [1, 10],
    division_name_en: "Singapore Nanyang Division",
    division_name_zh: "新加坡南洋赛区",
    division_code: "singapore_nanyang",
    competition: "Nanyang Star 2024 (Singapore Nanyang Division)"
  },
  {
    range: [11, 20],
    division_name_en: "Singapore KEC Division",
    division_name_zh: "新加坡KEC赛区",
    division_code: "singapore_kec",
    competition: "Nanyang Star 2024 (Singapore KEC Division)"
  },
  {
    range: [21, 30],
    division_name_en: "China Division",
    division_name_zh: "中国赛区",
    division_code: "china",
    competition: "Nanyang Star 2024 (China Division)"
  }
];

const artworkMetadata = [
  // 1-10: Singapore Nanyang Division
  {
    num: 1,
    title_en: "Harmony of Nanyang Gardens & Tropical Birds",
    title_zh: "南洋花园的和谐交响与热带飞鸟",
    artist_en: "Chloe Lim (Ages 11)",
    artist_zh: "林欣怡",
    ageGroup: "Pre-teen Group (age 9–12)",
    school: "Nanyang Girls' Primary School",
    discipline: "Chinese Painting",
    discipline_id: "DISC-CHP",
    category: "heritage_arts",
    medium: "Chinese Ink & Mineral Color on Xuan Paper (宣纸设色)",
    dimensions: "68 cm × 45 cm",
    award: "Star of Nanyang Grand Trophy (特等奖)",
    awardTier: "Grand Prize",
    desc_en: "Grand Prize laureate capturing vibrant Singapore flora, heritage shophouse silhouettes, and joyful tropical birds with fluid traditional brushstrokes.",
    desc_zh: "荣获新加坡南洋赛区特等奖，以娴熟的笔墨与浓郁的南洋色彩生动勾勒花园城市的和谐生态。"
  },
  {
    num: 2,
    title_en: "Sentosa Coral Reef Deep Ocean Odyssey",
    title_zh: "圣淘沙珊瑚秘境与深海探索",
    artist_en: "Lucas Tan (Ages 8)",
    artist_zh: "陈彦廷",
    ageGroup: "Children Group (age 6–8)",
    school: "Nan Hua Primary School",
    discipline: "Children Fine Arts",
    discipline_id: "DISC-CHD",
    category: "youth_arts",
    medium: "Soft Oil Pastel & Acrylic on Cartridge Paper",
    dimensions: "54 cm × 38 cm",
    award: "Gold Award (金奖)",
    awardTier: "Gold",
    desc_en: "Brilliant coral patterns and aquatic life rendered with rich, luminous color contrasts and imaginative underwater composition.",
    desc_zh: "以鲜艳明快的油画棒与亚克力结合，展现新加坡南部海域五彩斑斓的海洋生态奇景。"
  },
  {
    num: 3,
    title_en: "Emerald Hill Heritage Shophouses at Dusk",
    title_zh: "翡翠山百年排屋黄昏光影",
    artist_en: "Sarah Lim (Ages 14)",
    artist_zh: "林芷萱",
    ageGroup: "Youth Group (age 13–16)",
    school: "Methodist Girls' School",
    discipline: "Watercolor",
    discipline_id: "DISC-WTC",
    category: "fine_arts",
    medium: "Transparent Watercolor on 300gsm Arches Paper",
    dimensions: "56 cm × 38 cm",
    award: "Gold Award (金奖)",
    awardTier: "Gold",
    desc_en: "Masterful handling of light filtration and architectural ornament along historic Emerald Hill Peranakan terraces.",
    desc_zh: "运用细腻透亮的水彩技法，精准捕捉土生华人历史排屋在热带黄昏中的光影层次。"
  },
  {
    num: 4,
    title_en: "Calligraphy Scroll: Ode to the Nanyang Culture River",
    title_zh: "行书长卷《南洋文化长河颂》",
    artist_en: "Ethan Wang (Ages 12)",
    artist_zh: "王宇轩",
    ageGroup: "Pre-teen Group (age 9–12)",
    school: "Hwa Chong International School",
    discipline: "Chinese Calligraphy",
    discipline_id: "DISC-CLG",
    category: "heritage_arts",
    medium: "Traditional Pine Soot Ink on Gold-Spotted Paper (泥金宣纸)",
    dimensions: "138 cm × 34 cm",
    award: "Gold Award (金奖)",
    awardTier: "Gold",
    desc_en: "Dynamic semi-cursive script flowing with strength and classical rhythm, demonstrating mature Yan-style regular foundations.",
    desc_zh: "行草气脉贯通，骨力遒劲，展现青少年书法家对传统碑帖的深刻领悟与笔墨韵味。"
  },
  {
    num: 5,
    title_en: "Singapore Botanic Garden Tropical Symphony",
    title_zh: "新加坡植物园热带绿意交响",
    artist_en: "Hannah Lee (Ages 6)",
    artist_zh: "李涵雅",
    ageGroup: "Preschooler Group (age 4–6)",
    school: "MindChamps PreSchool",
    discipline: "Children Fine Arts",
    discipline_id: "DISC-CHD",
    category: "youth_arts",
    medium: "Wax Resist & Gouache Mixed Media",
    dimensions: "42 cm × 29 cm",
    award: "Silver Award (银奖)",
    awardTier: "Silver",
    desc_en: "Enchanting childhood depiction of ancient rain trees, orchids, and playful wildlife in UNESCO World Heritage grounds.",
    desc_zh: "充满童真童趣的蜡笔油水分离画，天真烂漫地展现热带雨林植物园的生机盎然。"
  },
  {
    num: 6,
    title_en: "Marina Bay Sunset Reflection",
    title_zh: "滨海湾落日倒影与现代天际线",
    artist_en: "Marcus Wong (Ages 15)",
    artist_zh: "黄子睿",
    ageGroup: "Youth Group (age 13–16)",
    school: "Anglo-Chinese School (Independent)",
    discipline: "Oil Painting",
    discipline_id: "DISC-OIL",
    category: "fine_arts",
    medium: "Oil on Linen Canvas (亚麻布油彩)",
    dimensions: "80 cm × 60 cm",
    award: "Silver Award (银奖)",
    awardTier: "Silver",
    desc_en: "Impasto knife strokes reflecting golden architectural glass reflections and vibrant Singapore harbor ripples.",
    desc_zh: "运用刮刀与厚涂技法，展现新加坡滨海湾摩天大楼与晚霞倒影的当代都市风貌。"
  },
  {
    num: 7,
    title_en: "Traditional Chinese Wayang Puppet Memories",
    title_zh: "传统戏台街头皮影木偶记忆",
    artist_en: "Natalie Teo (Ages 9)",
    artist_zh: "张乐萱",
    ageGroup: "Pre-teen Group (age 9–12)",
    school: "Raffles Girls' Primary School",
    discipline: "Cartoon Drawing",
    discipline_id: "DISC-CTN",
    category: "youth_arts",
    medium: "Color Ink & Fine Liner Illustration",
    dimensions: "40 cm × 30 cm",
    award: "Silver Award (银奖)",
    awardTier: "Silver",
    desc_en: "Imaginative character narrative reviving Singapore's historic temple street opera culture with lively cartoon expressions.",
    desc_zh: "融合现代插画与传统街戏元素，生动再现民间庙会传统皮影戏的民俗趣味。"
  },
  {
    num: 8,
    title_en: "Peranakan Heritage Tiles & Peacocks",
    title_zh: "土生华人花砖几何与祥瑞孔雀",
    artist_en: "Joshua Koh (Ages 10)",
    artist_zh: "许宇翔",
    ageGroup: "Pre-teen Group (age 9–12)",
    school: "St. Joseph's Institution Junior",
    discipline: "Academic Sketching",
    discipline_id: "DISC-SKT",
    category: "fine_arts",
    medium: "Graphite & Fine Ink Pen on Bristol Board",
    dimensions: "50 cm × 35 cm",
    award: "Bronze Award (铜奖)",
    awardTier: "Bronze",
    desc_en: "Intricate linear symmetry and geometric tile tessellations celebrating Straits Chinese decorative artistry.",
    desc_zh: "严谨的对称线条与繁复的娘惹花砖纹饰结合，体现出扎实的几何造型基本功。"
  },
  {
    num: 9,
    title_en: "Bukit Timah Rainforest Morning Mist",
    title_zh: "武吉知马热带雨林晨雾烟岚",
    artist_en: "Valerie Sim (Ages 13)",
    artist_zh: "沈佳欣",
    ageGroup: "Youth Group (age 13–16)",
    school: "Cedar Girls' Secondary School",
    discipline: "Chinese Painting",
    discipline_id: "DISC-CHP",
    category: "heritage_arts",
    medium: "Ink Wash on Sized Silk Fan (绢本设色)",
    dimensions: "60 cm × 60 cm",
    award: "Bronze Award (铜奖)",
    awardTier: "Bronze",
    desc_en: "Subtle boneless ink washes creating ethereal atmospheric perspective through dense virgin equatorial rainforest.",
    desc_zh: "将岭南设色与中国画水墨渲染相融，呈现热带原始雨林清晨的氤氲水气。"
  },
  {
    num: 10,
    title_en: "Smart Green Metropolis 2050",
    title_zh: "2050智能绿色生态大都会",
    artist_en: "Ryan Ng (Ages 7)",
    artist_zh: "黄凯文",
    ageGroup: "Children Group (age 6–8)",
    school: "Tao Nan School",
    discipline: "Children Fine Arts",
    discipline_id: "DISC-CHD",
    category: "youth_arts",
    medium: "Poster Color & 3D Recycled Origami",
    dimensions: "45 cm × 32 cm",
    award: "Excellence Award (优秀奖)",
    awardTier: "Excellence",
    desc_en: "Vibrant and inventive eco-futuristic cityscape featuring vertical sky trains and solar-powered floating islands.",
    desc_zh: "充满未来主义创意的环保城市构想，立意新颖，色彩鲜活饱满。"
  },

  // 11-20: Singapore KEC Division
  {
    num: 11,
    title_en: "KEC Creative Youth Art Odyssey",
    title_zh: "KEC少儿创意艺术启航与梦想之翼",
    artist_en: "Megan Low (Ages 11)",
    artist_zh: "刘美嘉",
    ageGroup: "Pre-teen Group (age 9–12)",
    school: "KEC International Academy",
    discipline: "Children Fine Arts",
    discipline_id: "DISC-CHD",
    category: "youth_arts",
    medium: "Acrylic & Soft Clay Relief on Heavy Panel",
    dimensions: "60 cm × 45 cm",
    award: "Star of Nanyang Grand Trophy (特等奖)",
    awardTier: "Grand Prize",
    desc_en: "Singapore KEC Division Grand Prize winner blending 3D clay relief elements with vivid expressive painting.",
    desc_zh: "新加坡KEC赛区特等奖作品，立体陶泥浮雕与亚克力颜料完美融合，极具艺术感染力。"
  },
  {
    num: 12,
    title_en: "The Historic Dragon Kiln of Jurong",
    title_zh: "裕廊陶光龙窑薪火不灭",
    artist_en: "Justin Chen (Ages 15)",
    artist_zh: "陈家豪",
    ageGroup: "Youth Group (age 13–16)",
    school: "Jurong Pioneer Junior College",
    discipline: "Academic Sketching",
    discipline_id: "DISC-SKT",
    category: "fine_arts",
    medium: "Charcoal & White Pastel on Kraft Paper",
    dimensions: "78 cm × 54 cm",
    award: "Gold Award (金奖)",
    awardTier: "Gold",
    desc_en: "Atmospheric study of Singapore's oldest surviving wood-fired dragon kiln, capturing dramatic kiln smoke and fiery embers.",
    desc_zh: "炭笔素描光影强烈，深刻刻画了新加坡仅存的木烧龙窑与陶瓷工艺历史底蕴。"
  },
  {
    num: 13,
    title_en: "National Flower Vanda Miss Joaquim & Golden Sun",
    title_zh: "卓锦万代兰盛放映朝阳",
    artist_en: "Emma Zhang (Ages 10)",
    artist_zh: "张雅婷",
    ageGroup: "Pre-teen Group (age 9–12)",
    school: "KEC Visual Arts Studio",
    discipline: "Chinese Painting",
    discipline_id: "DISC-CHP",
    category: "heritage_arts",
    medium: "Lingnan Boneless Method on Rice Paper (没骨法设色)",
    dimensions: "68 cm × 38 cm",
    award: "Gold Award (金奖)",
    awardTier: "Gold",
    desc_en: "Vibrant botanical study of Singapore's national orchid using delicate boneless mineral wash and calligraphic stems.",
    desc_zh: "以精湛的岭南没骨工笔，展现新加坡国花卓锦万代兰的高雅风韵与生机活力。"
  },
  {
    num: 14,
    title_en: "Old Chinatown Street Life Quick-Sketch",
    title_zh: "牛车水老街晨市生活速写",
    artist_en: "Daniel Tan (Ages 13)",
    artist_zh: "陈立威",
    ageGroup: "Youth Group (age 13–16)",
    school: "Chung Cheng High School (Main)",
    discipline: "Academic Sketching",
    discipline_id: "DISC-SKT",
    category: "fine_arts",
    medium: "Graphite Pencils (2B-6B) on Archival Cartridge",
    dimensions: "50 cm × 35 cm",
    award: "Silver Award (银奖)",
    awardTier: "Silver",
    desc_en: "Rapid observational drawing capturing lively pedestrian movement and timber shopfront textures in Chinatown.",
    desc_zh: "动态速写线条洗练流畅，富有生活气息，精准捕捉市井街巷的人文风情。"
  },
  {
    num: 15,
    title_en: "Deep Ocean Guardian & Coral Reef Cleaners",
    title_zh: "海洋生态卫士与清洁机器人",
    artist_en: "Sophie Wang (Ages 8)",
    artist_zh: "王雨晴",
    ageGroup: "Children Group (age 6–8)",
    school: "KEC Creative Arts Camp",
    discipline: "Children Fine Arts",
    discipline_id: "DISC-CHD",
    category: "youth_arts",
    medium: "Oil Pastels & Scratchboard Technique",
    dimensions: "45 cm × 32 cm",
    award: "Silver Award (银奖)",
    awardTier: "Silver",
    desc_en: "Youth environmental advocacy depicting futuristic marine robots rescuing sea turtles and coral gardens.",
    desc_zh: "充满生态环保情怀与童真幻想，刮画与油画棒技法相得益彰。"
  },
  {
    num: 16,
    title_en: "Calligraphy Couplet: Spirit of Integrity & Diligence",
    title_zh: "正楷五言联《笃行致远 · 厚德载物》",
    artist_en: "Kevin Liu (Ages 12)",
    artist_zh: "刘冠宇",
    ageGroup: "Pre-teen Group (age 9–12)",
    school: "KEC Chinese Cultural Centre",
    discipline: "Chinese Calligraphy",
    discipline_id: "DISC-CLG",
    category: "heritage_arts",
    medium: "Heavy Ink on Red Hand-Embroidered Scroll",
    dimensions: "100 cm × 25 cm × 2",
    award: "Silver Award (银奖)",
    awardTier: "Silver",
    desc_en: "Well-proportioned Regular Script couplets adhering to Tang Dynasty Ouyang Xun structural balance.",
    desc_zh: "结构严谨端庄，点画之间藏锋聚气，展现深厚扎实的楷书基本功。"
  },
  {
    num: 17,
    title_en: "Tropical Sunbird on Frangipani Branch",
    title_zh: "鸡蛋花枝头的热带太阳鸟",
    artist_en: "Rachel Goh (Ages 14)",
    artist_zh: "吴佩珊",
    ageGroup: "Youth Group (age 13–16)",
    school: "CHIJ St. Nicholas Girls' School",
    discipline: "Watercolor",
    discipline_id: "DISC-WTC",
    category: "fine_arts",
    medium: "Botanical Watercolor on Saunders Waterford 300gsm",
    dimensions: "48 cm × 36 cm",
    award: "Bronze Award (铜奖)",
    awardTier: "Bronze",
    desc_en: "Luminous floral transparency and iridescent bird feathers rendered with delicate wet-on-dry glazing.",
    desc_zh: "水彩水色交融，花瓣轻盈通透，羽毛光泽感刻画得细致入微。"
  },
  {
    num: 18,
    title_en: "Solar-Powered Urban Glider System",
    title_zh: "太阳能低空飞行器与城市森林",
    artist_en: "Brandon Lee (Ages 7)",
    artist_zh: "李梓阳",
    ageGroup: "Children Group (age 6–8)",
    school: "KEC Junior Workshop",
    discipline: "Cartoon Drawing",
    discipline_id: "DISC-CTN",
    category: "youth_arts",
    medium: "Alcohol Markers & Neon Pen on Smooth Bristol",
    dimensions: "40 cm × 30 cm",
    award: "Bronze Award (铜奖)",
    awardTier: "Bronze",
    desc_en: "Dynamic perspective cartoon drawing imagining pollution-free zero-gravity transit in Southeast Asia.",
    desc_zh: "线条利落，色彩鲜艳明朗，构图极具纵深感与现代科幻感。"
  },
  {
    num: 19,
    title_en: "Kampong Glam Sultan Mosque Reflection",
    title_zh: "苏丹回教堂金顶与古巷光影",
    artist_en: "Ashley Chua (Ages 16)",
    artist_zh: "蔡欣怡",
    ageGroup: "Youth Group (age 13–16)",
    school: "Temasek Junior College",
    discipline: "Oil Painting",
    discipline_id: "DISC-OIL",
    category: "fine_arts",
    medium: "Oil on Stretched Canvas",
    dimensions: "70 cm × 50 cm",
    award: "Bronze Award (铜奖)",
    awardTier: "Bronze",
    desc_en: "Warm golden twilight glazes contrasting with deep evening architectural shadows across Arab Street.",
    desc_zh: "色调浓郁典雅，精准再现新加坡甘榜格南历史街区的异域风情与晚霞。"
  },
  {
    num: 20,
    title_en: "Mid-Autumn Moonlit Lantern Festival",
    title_zh: "中秋月夜提灯游园乐",
    artist_en: "Bryan Heng (Ages 9)",
    artist_zh: "王嘉诚",
    ageGroup: "Pre-teen Group (age 9–12)",
    school: "KEC Art Education Center",
    discipline: "Children Fine Arts",
    discipline_id: "DISC-CHD",
    category: "youth_arts",
    medium: "Gouache & Glitter Gel on Black Paperboard",
    dimensions: "45 cm × 32 cm",
    award: "Excellence Award (优秀奖)",
    awardTier: "Excellence",
    desc_en: "Warm luminous glow of paper dragon lanterns and full moon reflecting off heritage park ponds.",
    desc_zh: "以黑色卡纸为底，烘托中秋提灯夜的暖光与欢庆气氛。"
  },

  // 21-30: China Division
  {
    num: 21,
    title_en: "Monumental Shanshui: Rivers and Mountains in Splendor",
    title_zh: "大美山河 · 千里江山万里云",
    artist_en: "Zhang Haoran (Ages 15)",
    artist_zh: "张浩然",
    ageGroup: "Youth Group (age 13–16)",
    school: "Beijing Central Academy Affiliated Middle School",
    discipline: "Chinese Painting",
    discipline_id: "DISC-CHP",
    category: "heritage_arts",
    medium: "Mineral Azurite & Malachite on 6-Foot Raw Xuan Paper (六尺青绿山水)",
    dimensions: "180 cm × 96 cm",
    award: "Star of Nanyang Grand Trophy (特等奖)",
    awardTier: "Grand Prize",
    desc_en: "China Division Grand Prize masterpiece combining monumental Northern Song landscape composition with vibrant blue-green mineral washes.",
    desc_zh: "荣膺中国赛区特等奖，气魄雄浑，青绿泼彩与密体披麻皴法相融，气韵万千。"
  },
  {
    num: 22,
    title_en: "Classical Peony in Imperial Bloom (Gongbi)",
    title_zh: "工笔重彩《国色天香盛世春》",
    artist_en: "Li Zihan (Ages 14)",
    artist_zh: "李子涵",
    ageGroup: "Youth Group (age 13–16)",
    school: "Shanghai Academy of Fine Arts Youth Studio",
    discipline: "Chinese Painting",
    discipline_id: "DISC-CHP",
    category: "heritage_arts",
    medium: "Multi-layered Mineral Glazes on Sized Silk (熟绢工笔设色)",
    dimensions: "90 cm × 60 cm",
    award: "Gold Award (金奖)",
    awardTier: "Gold",
    desc_en: "Over thirty translucent glazes creating depth and luminous gradients across delicate classical peony petals.",
    desc_zh: "层层三矾九染，设色典雅华贵，线条如行云流水，尽显传统工笔重彩之精妙。"
  },
  {
    num: 23,
    title_en: "Running Script Scroll: Li Bai's Poetic Masterpiece",
    title_zh: "行草长卷李白《将进酒》大作",
    artist_en: "Wang Yuxuan (Ages 15)",
    artist_zh: "王羽萱",
    ageGroup: "Youth Group (age 13–16)",
    school: "Hangzhou Classical Calligraphy Academy",
    discipline: "Chinese Calligraphy",
    discipline_id: "DISC-CLG",
    category: "heritage_arts",
    medium: "Dense Soot Ink on Handcrafted Dragon Xuan Paper",
    dimensions: "240 cm × 35 cm",
    award: "Gold Award (金奖)",
    awardTier: "Gold",
    desc_en: "Expressive calligraphic tempo echoing the passion and grand philosophical cadence of Tang Dynasty verse.",
    desc_zh: "笔势跌宕起伏，气势磅礴，提按顿挫极具感染力，深得宋明大家之神韵。"
  },
  {
    num: 24,
    title_en: "Classical Academic Plaster Study: David",
    title_zh: "全因素学院派素描《大卫石膏切面与肖像》",
    artist_en: "Chen Yichen (Ages 16)",
    artist_zh: "陈奕辰",
    ageGroup: "Youth Group (age 13–16)",
    school: "Guangzhou Academy of Fine Arts High School",
    discipline: "Academic Sketching",
    discipline_id: "DISC-SKT",
    category: "fine_arts",
    medium: "Graphite Pencils (H-8B) on 4-Cut Archival Board",
    dimensions: "78 cm × 54 cm",
    award: "Gold Award (金奖)",
    awardTier: "Gold",
    desc_en: "Flawless anatomical precision and 5-tier chiaroscuro value scales demonstrating high academic standard.",
    desc_zh: "严谨的西方古典学院派素描，骨骼比例精准，黑白灰五大调子过渡细腻自然。"
  },
  {
    num: 25,
    title_en: "Jiangnan Water Village at Dawn",
    title_zh: "江南水乡晨雾轻舟",
    artist_en: "Liu Mengyao (Ages 12)",
    artist_zh: "刘梦瑶",
    ageGroup: "Pre-teen Group (age 9–12)",
    school: "Suzhou Youth Cultural Center",
    discipline: "Watercolor",
    discipline_id: "DISC-WTC",
    category: "fine_arts",
    medium: "Wet-in-Wet Watercolor on Cotton Rag Paper",
    dimensions: "54 cm × 38 cm",
    award: "Silver Award (银奖)",
    awardTier: "Silver",
    desc_en: "Poetic watercolor atmosphere of white-walled heritage residences along misty morning canals.",
    desc_zh: "水色淋漓，诗意盎然，水晕墨章般呈现江南古镇小桥流水人家的清雅晨景。"
  },
  {
    num: 26,
    title_en: "Dunhuang Mogao Caves Flying Apsaras",
    title_zh: "敦煌莫高窟飞天霓裳羽衣",
    artist_en: "Zhao Junjie (Ages 11)",
    artist_zh: "赵俊杰",
    ageGroup: "Pre-teen Group (age 9–12)",
    school: "Dunhuang Art Heritage Youth Academy",
    discipline: "Chinese Painting",
    discipline_id: "DISC-CHP",
    category: "heritage_arts",
    medium: "Mineral Ochre, Malachite & Gold Foil on Hemp Paper",
    dimensions: "68 cm × 68 cm",
    award: "Silver Award (银奖)",
    awardTier: "Silver",
    desc_en: "Rich historical resonance inspired by Thousand Buddha Caves mural frescoes with authentic mineral pigmentation.",
    desc_zh: "汲取敦煌莫高窟壁画精髓，沥粉贴金与矿物颜料交相辉映，灵动飘逸。"
  },
  {
    num: 27,
    title_en: "Intangible Cultural Heritage Papercutting & Childhood",
    title_zh: "非遗剪纸窗花与童真童趣",
    artist_en: "Zhou Yitong (Ages 8)",
    artist_zh: "周怡彤",
    ageGroup: "Children Group (age 6–8)",
    school: "Shaanxi Folk Art Youth Workshop",
    discipline: "Children Fine Arts",
    discipline_id: "DISC-CHD",
    category: "youth_arts",
    medium: "Intricate Papercut Relief & Acrylic Mixed Media",
    dimensions: "45 cm × 35 cm",
    award: "Silver Award (银奖)",
    awardTier: "Silver",
    desc_en: "Traditional folk papercutting artistry interwoven with childhood games and joyful village motifs.",
    desc_zh: "将民间传统剪纸技艺与现代少儿美术巧妙结合，红亮热烈，民俗韵味浓郁。"
  },
  {
    num: 28,
    title_en: "High-Speed Rail Across Emerald Valleys",
    title_zh: "复兴号高铁穿越青山绿水",
    artist_en: "Sun Mingxuan (Ages 9)",
    artist_zh: "孙铭轩",
    ageGroup: "Children Group (age 6–8)",
    school: "Chengdu Youth Art Center",
    discipline: "Children Fine Arts",
    discipline_id: "DISC-CHD",
    category: "youth_arts",
    medium: "Gouache & Fine Graphic Markers",
    dimensions: "50 cm × 35 cm",
    award: "Bronze Award (铜奖)",
    awardTier: "Bronze",
    desc_en: "Bold dynamic diagonal composition celebrating modern clean transport traversing lush ecological mountain passes.",
    desc_zh: "对角线构图极具冲击力，生动描绘现代高铁穿行于绿色生态山川的壮美景象。"
  },
  {
    num: 29,
    title_en: "Clerical Script: Han Dynasty Stone Inscription Couplet",
    title_zh: "汉隶《张迁碑》意趣七言对联",
    artist_en: "Guo Yuhan (Ages 13)",
    artist_zh: "郭雨涵",
    ageGroup: "Youth Group (age 13–16)",
    school: "Xi'an Stele Forest Calligraphy Class",
    discipline: "Chinese Calligraphy",
    discipline_id: "DISC-CLG",
    category: "heritage_arts",
    medium: "Dark Ink on Red Batik Xuan Paper (蜡染宣纸)",
    dimensions: "120 cm × 30 cm × 2",
    award: "Bronze Award (铜奖)",
    awardTier: "Bronze",
    desc_en: "Silkworm-head and swallow-tail Han Dynasty clerical brush strokes exhibiting ancient stone-carving sturdiness.",
    desc_zh: "蚕头燕尾，古朴雄浑，深得汉代汉碑摩崖石刻之金石古风。"
  },
  {
    num: 30,
    title_en: "Future Green Solar Planet Utopia",
    title_zh: "未来绿色星球太阳能理想国",
    artist_en: "Lin Zirui (Ages 7)",
    artist_zh: "林子睿",
    ageGroup: "Children Group (age 6–8)",
    school: "Nanjing Art Academy Junior Studio",
    discipline: "Children Fine Arts",
    discipline_id: "DISC-CHD",
    category: "youth_arts",
    medium: "Acrylic, Clay & Metallic Leaf on Cardboard",
    dimensions: "45 cm × 32 cm",
    award: "Excellence Award (优秀奖)",
    awardTier: "Excellence",
    desc_en: "Vibrant multi-dimensional vision of sustainable cosmic cities with clean green atmosphere.",
    desc_zh: "丰富多元的混合材质展现出浩瀚无垠的绿色星际探索梦。"
  }
];

// Generate GalleryArtworks Array
const galleryArtworks = artworkMetadata.map((art) => {
  const divInfo = divisions.find(d => art.num >= d.range[0] && art.num <= d.range[1]);
  return `    {
      id: "GAL-ART-${String(art.num).padStart(2, '0')}",
      title: "${art.title_en.replace(/"/g, '\\"')}",
      title_zh: "${art.title_zh}",
      artist: "${art.artist_en}",
      artist_zh: "${art.artist_zh}",
      artistType: "student_laureate",
      division: "${divInfo.division_name_en} (${divInfo.division_name_zh})",
      division_slug: "${divInfo.division_code}",
      year: 2024,
      category: "${art.category}",
      discipline: "${art.discipline}",
      discipline_id: "${art.discipline_id}",
      dimensions: "${art.dimensions}",
      medium: "${art.medium}",
      competition: "${divInfo.competition}",
      award: "${art.award}",
      awardTier: "${art.awardTier}",
      exhibition: "Nanyang Star 2024 Laureates Salon (Singapore Federation of Art Societies Gallery)",
      description: "${art.desc_en.replace(/"/g, '\\"')}",
      description_zh: "${art.desc_zh}",
      imageUrl: "assets/images/art-works/art-${art.num}.png",
      highResUrl: "assets/images/art-works/art-${art.num}.png",
      aspectRatio: "${art.num % 3 === 0 ? 'portrait' : 'landscape'}",
      contentStatus: "verified"
    }`;
}).join(',\n');

// Generate CompetitionWinners Array
const competitionWinners = artworkMetadata.map((art) => {
  const divInfo = divisions.find(d => art.num >= d.range[0] && art.num <= d.range[1]);
  const isSpotlight = art.awardTier === "Grand Prize";
  return `    {
      id: "WIN-2024-${String(art.num).padStart(2, '0')}",
      year: 2024,
      competitionId: "COMP-NANYANG-2024",
      name: "${art.artist_en}",
      chineseName: "${art.artist_zh}",
      ageGroup: "${art.ageGroup}",
      division: "${divInfo.division_name_en} (${divInfo.division_name_zh})",
      division_slug: "${divInfo.division_code}",
      award: "${art.award}",
      awardTier: "${art.awardTier}",
      region: "${divInfo.division_name_en}",
      school: "${art.school}",
      isSpotlight: ${isSpotlight},
      artwork: {
        title: "${art.title_en.replace(/"/g, '\\"')}",
        title_zh: "${art.title_zh}",
        medium: "${art.medium}",
        imageUrl: "assets/images/art-works/art-${art.num}.png"
      },
      juryComment_en: "${art.desc_en.replace(/"/g, '\\"')}",
      juryComment_zh: "${art.desc_zh}",
      status: "verified"
    }`;
}).join(',\n');

// Replace GalleryArtworks in dbContent
const galleryArtworksRegex = /GalleryArtworks:\s*\[[\s\S]*?\],\s*Competitions:/;
dbContent = dbContent.replace(galleryArtworksRegex, `GalleryArtworks: [\n${galleryArtworks}\n  ],\n\n  Competitions:`);

// Replace CompetitionWinners in dbContent
const compWinnersRegex = /CompetitionWinners:\s*\[[\s\S]*?\],\s*TestCentres:/;
dbContent = dbContent.replace(compWinnersRegex, `CompetitionWinners: [\n${competitionWinners}\n  ],\n\n  TestCentres:`);

fs.writeFileSync(dbFilePath, dbContent, 'utf8');
console.log('Successfully updated GalleryArtworks and CompetitionWinners with 30 artworks in db.js!');
